### PR TITLE
To get catpure volume, capture channel is used.

### PR DESCRIPTION
**Pull request by nlewo**

### CODE REVIEW

**Comment by nlewo** [comment]
fixes #4

**Comment by ttuegel** [comment]
Looks good, but could you change the commit message to "Use capture channel to get capture volume"? I'd do it myself from the command-line, but then you won't show up as a contributor on GitHub :smiley:

**Comment by nlewo** [comment]
I udpated the commit message as you mentionned.

Should it be possible to push a new release to hackage since this fix is required by this PR https://github.com/jaor/xmobar/pull/251?

**Comment by ttuegel** [comment]
Yes, I'll push a new release to Hackage today. Thanks!

**Comment by nlewo** [comment]
Thomas Tuegel <notifications@github.com> writes:

> Yes, I'll push a new release to Hackage today. Thanks!

Ok, great. Thanks.

**Pull request merged**
